<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="MediatR" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <ProjectReference Include="..\TradeMind.ExecutionSessions.Domain\TradeMind.ExecutionSessions.Domain.csproj" />
  </ItemGroup>
</Project>
