<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.4" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.4" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="9.0.4" />
    <ProjectReference Include="..\TradeMind.AI.Agents\TradeMind.AI.Agents.csproj" />
    <ProjectReference Include="..\TradeMind.AI.Application\TradeMind.AI.Application.csproj" />
  </ItemGroup>

</Project>
